version: '3.8'

services:
  lambda:
    build: .
    volumes:
      - .:/var/task
    environment:
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=1600
      - AWS_LAMBDA_FUNCTION_TIMEOUT=30
    ports:
      - "9000:8080" 